[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[theme]
base="dark"

[browser]
gatherUsageStats = false

[client]
showErrorDetails = true

[ui]
hideTopBar = true
